### ISSUE TITLE
How to modify Order and Order item (URGENT)

### ISSUE THREAD

**Issue by jofomah** [Mozu/mozu-node-sdk#19]
Hi

I am currently writing a Mozu app that defines a handler for this action `embedded.commerce.orders.action.before` the whole idea is to be able  to update order items, delete order items or order itself.

I can't see any concrete example on how to modify an order inside `embedded.commerce.orders.action.before` handler.

Also when i call `https://www.mozu.com/docs/api/commerce/orders/operations/deleteorderitem.htm` via Mozu SDk, it throws permission error. also when i try to delete an order via mozu sdk client it throws permission error.

The system does not permit the attempted operation.  Not authorized to perform 'Order/UpdateItemQuantity' 
 additionalErrorData: [ { name: 'OperationName',
    value: 'Not authorized to perform \'Order/UpdateItemQuantity\'' } ]
 items: []
 statusCode: 403

Also, how do i dynamically modify order item quantity, remove order item from order inside `embedded.commerce.orders.action.before` handler.

Thanks

**Comment by sanjaymandadi** [comment]
when using API's outside of Arc you will need to add behaviors in dev center application

Application -> packages -> behaviors. 

for this particular api call you will need order update behavior

**Comment by jofomah** [comment]
@sanjaymandadi thanks, i have done this but yet when i try to delete an order item i get permission error.

Do you have a sample code, blog or resource on how to dynamically modify order etc??

**Comment by jofomah** [comment]
or can i get an example of how to modify order items using `context.exec()`
