### ISSUE TITLE
CustomerAccount GetAccount is not working with  V 2.13

### ISSUE THREAD

**Issue by sridhar-acehardware** [Mozu/mozu-node-sdk#24]
**mozu-node-sdk/clients/commerce/customer/customerAccount**=>

	getAccount: Client.method({
		method: constants.verbs.GET,
		url: '{+tenantPod}api/commerce/customer/accounts/{accountId}**&userId={userId}**?responseFields={responseFields}'
	})

URL should be 
url: '{+tenantPod}api/commerce/customer/accounts/{accountId}?userId={userId}&responseFields={responseFields}

**Comment by kibo-thomasphipps** [comment]
closing old fixed issue
